MIWeb:
  Nodes:
    fallbackNode:
      nodeType: 'plain'
      attributes:
        content: '404 - Page not found'
    nodeTypes:
      'plain':
        class: 'MIWeb\Nodes\NodeTypes\PlainNode'
        defaults:
          content: '[empty]'
      'template':
        class: 'MIWeb\Nodes\NodeTypes\SimpleTemplateNode'
        defaults:
          templateSource: '[empty]'
      'fluid':
        class: 'MIWeb\Nodes\NodeTypes\FluidNode'
    nodeEditors:
      textfield:
        viewhelper: 'Neos\FluidAdaptor\ViewHelpers\Form\TextfieldViewHelper'
      textarea:
        viewhelper: 'Neos\FluidAdaptor\ViewHelpers\Form\TextareaViewHelper'
      html:
        viewhelper: 'Neos\FluidAdaptor\ViewHelpers\Form\TextareaViewHelper'

